### ISSUE TITLE
History Time To Live cannot be null

### ISSUE THREAD

**Issue by mrynasiewicz** [camunda-community-hub/camunda-platform-7-rest-client-java#111]
I'm trying to deploy process using api deploymentApi.createDeployment. Unfortunately I have error:
Caused by: org.camunda.community.rest.client.invoker.ApiException: {"type":"ParseException","message":"ENGINE-09005 Could not parse BPMN process. Errors: \n* History Time To Live cannot be null: History Time To Live cannot be null}
I found in the documentation that I need to set the property camunda.bpm.generic-properties.properties.historyTimeToLive
https://forum.camunda.io/t/camunda-7-20-history-time-to-live-cannot-be-null-cannot-deploy-wf-created-in-7-18/48159

or change default value enforceHistoryTimeToLive to false
https://docs.camunda.org/manual/latest/reference/deployment-descriptors/tags/process-engine/?_gl=1*116lgtf*_ga*MjAwNzkwOTQ5My4xNjg0OTk3MDM0*_ga_4EYN8X5FNR*MTcwNTM0NzIxMy4yMi4xLjE3MDUzNDczMzguNTkuMC4w#configuration-properties

Setting in application.yml file:
```
camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D
```
don't work.

How can I set this value using camunda-platform-7-rest-client-java library?

**Comment by jonathanlukas** [comment]
@mrynasiewicz the property to set a default history time to live is set to the engine.

If you want to have a default TTL being set by this client, you should provide a feature request.
