### ISSUE TITLE
Could not autowire. No beans of 'IncidentApi' type found. 

### ISSUE THREAD

**Issue by JimmyYouhei** [camunda-community-hub/camunda-platform-7-rest-client-java#116]
When using Spring rest client api when inject IncidentApi there is error :

<img width="1120" alt="Untitled" src="https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/assets/37929072/4b09f089-d82e-4c96-ae60-b6400845103e">

and Spring boot is unable to boot

I am currently using 7.20.4 version and Spring boot 3.1.7

**Comment by alex-fgsfds** [comment]
The same problem on Spring Boot 3.2.4. Does it work on Spring Boot 3 then? Indeed, I do not see the required annotations on the ProcessDefinitionApi class, for example. It seems that defining a `@Configuration` with corresponding bean factory methods solves this particular issue.
![image](https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/assets/13852968/50b892aa-29f4-494e-80eb-e141ecb9aed6)

**Comment by jonathanlukas** [comment]
Does this work with `7.20.5`?

If not, I will have to dig deeper as the artefacts should contain the spring boot 3 style autoconfiguration.imports

**Comment by hauch** [comment]
It's simply missing in CamundaApi.
One workaround is to add it manually in class annotated with Configuration:
`@Bean
    public IncidentApi incidentApi() {
        return new IncidentApi(apiClient);
    }`
