### ISSUE TITLE
null/'[]'/other values instead of exceptions

### ISSUE THREAD

**Issue by NewbieProger** [camunda-community-hub/camunda-platform-7-rest-client-java#13]
Why every request call i should catch exceptions? Seriously? When I have reponse like '[]', when empty massive whe chould catch exception??? And how I should understand - exception was cos of '[]' or something with apiclient? or couldnt deserialize? or didnt found defenition key?

**Comment by berndruecker** [comment]
Could you please ask via the https://forum.camunda.io/ and also provide a bit more content what you are referring to? Thx!
