### ISSUE TITLE
The client tries to connect to 127.0.0.1:8080 regardless of what is given in configs

### ISSUE THREAD

**Issue by farhangamary** [camunda-community-hub/camunda-platform-7-rest-client-java#26]
In **application.yml**, I have:
```
camunda.bpm.client:
  base-url: http://localhost:8081/engine-rest
```

The ApiClient takes no argument for constructor and I found no method to set a host/port for it.

dependency:
```
		<dependency>
			<groupId>org.camunda.community</groupId>
			<artifactId>camunda-engine-rest-client-openapi-java</artifactId>
			<version>7.17.0</version>
		</dependency>
```

 Port 8080 is not in use by any other service/apput and I always get following exception : 

```
org.camunda.community.rest.client.invoker.ApiException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
	at org.camunda.community.rest.client.invoker.ApiClient.execute(ApiClient.java:913)
	at org.camunda.community.rest.client.api.MessageApi.deliverMessageWithHttpInfo(MessageApi.java:148)
	at org.camunda.community.rest.client.api.MessageApi.deliverMessage(MessageApi.java:127)
```

in

`new MessageApi(client).deliverMessage(new CorrelationMessageDto().messageName("paymentRquestMessage")`

Any Idea!!???

**Comment by berndruecker** [comment]
@farhangamary I think this should be within the setBasePath? https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/blob/main/camunda-engine-rest-client-openapi-springboot/src/main/java/org/camunda/community/rest/client/springboot/CamundaOpenApiStarter.java#L18 Does that work for you?

**Comment by farhangamary** [comment]
@berndruecker , Yes that worked. I had to set the basePath. 
Thank you.

**Comment by berndruecker** [comment]
@farhangamary  Should we update the readme?

**Comment by berndruecker** [comment]
Yeah - great - then you can send a Pull Request maybe?

**Comment by farhangamary** [comment]
Sure - I will - by the end of the day.
