### ISSUE TITLE
Incompatible okhttp version

### ISSUE THREAD

**Issue by hoestreich** [camunda-community-hub/camunda-platform-7-rest-client-java#41]
Playing around with the java client I think I discovered an incompability to the `camunda-engine-rest-openapi`.

The openapi lib uses version 3.14.2 of the okhttp3 dependency (see https://github.com/camunda/camunda-bpm-platform/blob/a3137428e8598121095f472161ff9183a85f2233/engine-rest/engine-rest-openapi/pom.xml), while this repo declares version 4.9.3 of the okhttp3 dep.

The problem occures when I try to deploy a process with the `DeploymentApi`. The incompability is located in the `buildRequestBodyMultipart` method of the auto-generated `ApiClient` class. The okhttp3 lib changed the parameter order of the `RequestBody.create` method between version 3 and 4.

In my opinion updating the dependency in camunda-engine-rest-openapi repo would be possible and solves the problem.

Best regards, Hendrik

**Comment by berndruecker** [comment]
Thanks @hoestreich for raising this! I would love pull in @ThorbenLindhauer as his team takes care of camunda-engine-rest-openapi. For me it sounds reasonable to update the library there, but I am not sure about other consequences that change might have.

**Comment by ThorbenLindhauer** [comment]
Hi, not sure I get what the goal here is. `okhttp` is a test dependency in https://github.com/camunda/camunda-bpm-platform/blob/a3137428e8598121095f472161ff9183a85f2233/engine-rest/engine-rest-openapi/pom.xml so how does changing the version have an impact on depending modules?

**Comment by hoestreich** [comment]
Hi!
I'm not an expert on the openapi generation stuff, but somehow the generated `DeploymentApi` internally seems to use version 3 of the `okhttp` dependency. Maybe because the `<classpathScope>test</classpathScope>` (https://github.com/camunda/camunda-bpm-platform/blob/a3137428e8598121095f472161ff9183a85f2233/engine-rest/engine-rest-openapi/pom.xml#L133) is defined?

**Comment by ThorbenLindhauer** [comment]
Here's the documentation for the `java` code generator of the `openapi-generator-maven-plugin` that this project uses: https://openapi-generator.tech/docs/generators/java/. Under `library`, it lists `okhttp-gson` as the default and that this uses `OkHttp 3.x`. Accordingly, I believe that this plugin is currently not capable of generating OkHttp 4 code and you should look into that direction.

**Comment by hoestreich** [comment]
Hi @ThorbenLindhauer,
thanks for investigating the issue. I guess manually increasing the version in the `engine-rest-openapi` project is not a good option, as it can lead to other incompatibilities. For me, increasing the `okhttp-version` in the `engine-rest-openapi` project worked, but I understand that you may want to avoid that.
I'm not sure, if @berndruecker wants to decrease the version here (I haven't tested if that works)...
Since my workaround is currently working for me, feel free to close the issue.

**Comment by ThorbenLindhauer** [comment]
> For me, increasing the okhttp-version in the engine-rest-openapi project worked, ...

I really curious why this would be the case because I find it hard to believe :). Can you share a minimal project in which you observe the problem (and in which changing the version in the `engine-rest-openapi` dependency then makes a difference)?

**Comment by hoestreich** [comment]
I'm pretty busy right now, but I'll try to share a project with you in the next week.

**Comment by hoestreich** [comment]
Ok, I took some time today to set up a minimal sample project from scratch to see that you were right. (@ThorbenLindhauer). 
It must have been a temporary incorrect dependency definition in my own project that caused the errors.
I apologize for the inconvenience I caused. 
So I'm closing the issue myself.

**Comment by ThorbenLindhauer** [comment]
No worries, glad you could figure it out :)
