### ISSUE TITLE
Service start fails if engine is down

### ISSUE THREAD

**Issue by sumant1801** [camunda-community-hub/camunda-platform-7-rest-client-java#54]
As per current behavior there is no try catch in bpmn auto deploy, if for any reason, if engine is down, the service will not boot. It will be good to have a flag to ignore deployment error and let the service boot.
fixing the same in https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/pull/50

**Comment by berndruecker** [comment]
Just merged the PR
