### ISSUE TITLE
Change "changed-only" and "enable-duplicate-filtering" flag to String

### ISSUE THREAD

**Issue by samanthacatania** [camunda-community-hub/camunda-platform-7-rest-client-java#82]
I have recently been in touch with Camunda support because when deploying the BPMN files through the API, the version was being increased even though we're setting the _changedOnly_ and _duplicateFiltering_ flags as true. After a lot of back and forth and troubleshooting it turns out that the Camunda API expects a string with "true" or "false" and not a boolean as described in the Swagger.

https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/blob/ccbd6e983f490e91274225137c1cd85d9f908825/camunda-engine-rest-client-openapi-springboot/src/main/java/org/camunda/community/rest/client/springboot/CamundaProcessAutodeployment.java#L93-L94

https://github.com/camunda/camunda-bpm-platform/issues/3736

**Comment by jonathanlukas** [comment]
Hello @samanthacatania , this issue does belong the official camunda-bpm repo as here, the openApi json is just used for client generation: https://github.com/camunda/camunda-bpm-platform
