### ISSUE TITLE
[Feature Request] v8

### ISSUE THREAD

**Issue by alex-hedley** [camunda-community-hub/camunda-platform-7-rest-client-java#85]
Has anyone started working on a v8?
Would this be done in a new repo?

**Comment by berndruecker** [comment]
@alex-hedley Do you mean Camunda 8? This would be a new repo. 
There was a community effort once started here: https://github.com/korthout/camunda-platform-rest-api - but I don't think it is actively maintained. We also discuss this matter internally at the moment if we shall/can provide a REST API for Camunda 8 (ping @akeller FYI)

**Comment by alex-hedley** [comment]
I did.
Is it worth seeing if it can be moved over to the `camunda-community-hub` org?

**Comment by berndruecker** [comment]
@korthout: WDYT - would it make sense to transfer the repo to the community hub (maybe renaming it to `camunda-community-hub/camunda-platform-8-rest-client-java` to make it clearly distinguishable from this repo)?

**Comment by alex-hedley** [comment]
I meant asking @korthout to move `https://github.com/korthout/camunda-platform-rest-api` for better visibility, it might allow for other maintainers and it keeps like for like together in one place.

**Comment by korthout** [comment]
@berndruecker I've let maintenance of https://github.com/korthout/camunda-platform-rest-api slip for two reasons:
- there was not much actual interest from the community. Some people visited the repo, but no feature requests, bug reports, contributions, or other feedback were brought to my attention, apart from some people mentioning that the idea is good. 
- the project is hard to maintain for the entire camunda 8 platform. Any additional APIs or API changes must be reflected in the code in that project. I was pushing for an alternative approach, but that did not find traction yet. Alternatively, it might make sense to re-focus the project to Zeebe alone, as most of the Camunda 8 components already have a REST API except for Zeebe.

@alex-hedley What additional value do you see as in moving the project over to the `camunda-community-hub`? I'd like to understand what value this would provide before spending time on this. Please consider that this would require changes to the CI and release process and that this costs time to change and test. Would moving the project help you to use the project? If so, how? Would it help you to contribute to it? If so, how?

I'd also like to know whether users are actually interested in using this project, before spending more time on it. At the moment, there appears to be little interest. I cannot track actual usage, so I depend on community outreach for this knowledge.

**Comment by alex-hedley** [comment]
I guess visibility for one, if people are looking for Camunda stuff it seems to be the place to go.
Might have more a seal of approval on it is on a semi-official org.
It would allow for more maintainers as it's then not just a single user repo.
Happy to help adding any issues/feature requests for the missing functionality so it's easier to track what is left to do? Maybe even create a Project board.
