### ISSUE TITLE
Update to Camunda 7.20 (so that Spring Boot 3 can be used)

### ISSUE THREAD

**Issue by cagdasoezguer** [camunda-community-hub/camunda-platform-7-rest-client-java#86]

**Comment by cagdasoezguer** [comment]
This blocks our migration to Spring Boot 3

**Comment by berndruecker** [comment]
Updated with https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/commit/b3544a1dda259f9297dd5dd4ea7a2b5799a1a85d

**Comment by berndruecker** [comment]
But why was this blocking he usage of Spring Boot 3? As this lib "just" communicates via REST it should also be able to use SB3 with 7.19?

**Comment by berndruecker** [comment]
I will also bump the SB version in the pom to the latest version.

**Comment by berndruecker** [comment]
It come up in another discussion, that we needed to adjust the way AutoConfiguration works for SB3 compatibility, which we just released with the latest version: https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/pull/88 - so this should be also solved now
